/usr/local/lib/python3.4/dist-packages/rpi_rf/rpi_rf.py:77: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(self.gpio, GPIO.OUT)
/tmp/nanocul.log
Traceback (most recent call last):
  File "/home/matthias/git/caltimer/nanocul_receive.py", line 328, in <module>
    main()
  File "/home/matthias/git/caltimer/nanocul_receive.py", line 301, in main
    data = ser.read(9999)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 453, in read
    buf = os.read(self.fd, size-len(read))
BlockingIOError: [Errno 11] Resource temporarily unavailable
